version: '3.12'

services:
  backend:
    build:
      context: ./backend
      dockerfile: /Dockerfile
    container_name: micontenedorback
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    env_file:
      - .env  # Carga las variables de entorno desde .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - .env  # Carga las credenciales desde .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
